FROM golang:1.17.1-alpine as build
WORKDIR /go/src/app

RUN apk update && apk --no-cache add git
COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN go build main.go

FROM alpine:latest
WORKDIR /root

COPY --from=build /go/src/app/ /root

ENV GIN_MODE=release

EXPOSE 3000
CMD ["/root/main"]
